
# Targeting minima theme version in '2.5-stable' branch including the google-analytics.html fix/update.
remote_theme: jekyll/minima@478d99d

title: Ben42Code's Blog
tagline: Sharing my journey in coding and technology
description: Personal blog and portfolio of Ben42Code

repository: ben42code/ben42code.github.io
github_username: ben42code

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author: Ben42Code
email: ben.42.code+githubio@gmail.com

exclude:
  - Dockerfile

collections:
  mypages:
    output: true

google_analytics: G-SMMZN59NRR

show_excerpts: true
strict_front_matter: true